({
    getIconForName: function(component, event, helper, configurationObject) {
        var iconsNameValuePair = component.get("v.iconsNameValuePair");
        var iconValue = '';
		
        for (var i = 0; i < iconsNameValuePair.length; i++) {
            if (iconsNameValuePair[i].Name.toLowerCase() == configurationObject.IconName.toLowerCase()) {
                iconValue = iconsNameValuePair[i].Value;
                break;
            }
        }
        
        return iconValue;
    },
    initializeIconsArray: function(component, event, helper, configurationObject) {
        var iconsNameValuePair = component.get("v.iconsNameValuePair");
        if (iconsNameValuePair.length == 0) {
            iconsNameValuePair.push({'Name':'Heart (Full)', 'Value':'10084'});
            iconsNameValuePair.push({'Name':'Ellipses', 'Value':'&#59392;'});
            iconsNameValuePair.push({'Name':'Calendar Day', 'Value':'&#59393;'});
            iconsNameValuePair.push({'Name':'Plus', 'Value':'&#59394;'});
            iconsNameValuePair.push({'Name':'Add User', 'Value':'&#59395;'});
            iconsNameValuePair.push({'Name':'Announcemet', 'Value':'&#59396;'});
            iconsNameValuePair.push({'Name':'Link/Url', 'Value':'&#59397;'});
            iconsNameValuePair.push({'Name':'Left', 'Value':'&#59398;'});
            iconsNameValuePair.push({'Name':'Bell/Alarm', 'Value':'&#59399;'});
            iconsNameValuePair.push({'Name':'Ribbon', 'Value':'&#59400;'});
            iconsNameValuePair.push({'Name':'Phone', 'Value':'&#59401;'});
            iconsNameValuePair.push({'Name':'Chat', 'Value':'&#59402;'});
            iconsNameValuePair.push({'Name':'Check', 'Value':'&#59403;'});
            iconsNameValuePair.push({'Name':'Map Pin', 'Value':'&#59404;'});
            iconsNameValuePair.push({'Name':'Lesser Than/Previous', 'Value':'&#59405;'});
            iconsNameValuePair.push({'Name':'Greater Than/Next', 'Value':'&#59406;'});
            iconsNameValuePair.push({'Name':'Cancel (X)', 'Value':'&#59407;'});
            iconsNameValuePair.push({'Name':'Hyphen/Minus', 'Value':'&#59408;'});
            iconsNameValuePair.push({'Name':'Computer Monitor', 'Value':'&#59409;'});
            iconsNameValuePair.push({'Name':'Down Arrow', 'Value':'&#59410;'});
            iconsNameValuePair.push({'Name':'Download', 'Value':'&#59411;'});
            iconsNameValuePair.push({'Name':'Email', 'Value':'&#59412;'});
            iconsNameValuePair.push({'Name':'Wrong Way', 'Value':'&#59413;'});
            iconsNameValuePair.push({'Name':'Calendar', 'Value':'&#59414;'});
            iconsNameValuePair.push({'Name':'Full Star', 'Value':'&#59415;'});
            iconsNameValuePair.push({'Name':'Filter', 'Value':'&#59416;'});
            iconsNameValuePair.push({'Name':'Category Filter', 'Value':'&#59417;'});
            iconsNameValuePair.push({'Name':'Snowflake', 'Value':'&#59418;'});
            iconsNameValuePair.push({'Name':'Users Group/Team', 'Value':'&#59419;'});
            iconsNameValuePair.push({'Name':'Question Mark', 'Value':'&#59420;'});
            iconsNameValuePair.push({'Name':'Image', 'Value':'&#59421;'});
            iconsNameValuePair.push({'Name':'Info', 'Value':'&#59422;'});
            iconsNameValuePair.push({'Name':'Left Arrow', 'Value':'&#59423;'});
            iconsNameValuePair.push({'Name':'Thumbs Up', 'Value':'&#59424;'});
            iconsNameValuePair.push({'Name':'Link/Url', 'Value':'&#59425;'});
            iconsNameValuePair.push({'Name':'Checklist', 'Value':'&#59426;'});
            iconsNameValuePair.push({'Name':'Map', 'Value':'&#59427;'});
            iconsNameValuePair.push({'Name':'Close Lock', 'Value':'&#59428;'});
            iconsNameValuePair.push({'Name':'Upload Right', 'Value':'&#59429;'});
            iconsNameValuePair.push({'Name':'Magic Wand', 'Value':'&#59430;'});
            iconsNameValuePair.push({'Name':'Plus', 'Value':'&#59431;'});
            iconsNameValuePair.push({'Name':'Phone Base', 'Value':'&#59432;'});
            iconsNameValuePair.push({'Name':'Notebook/Notepad', 'Value':'&#59433;'});
            iconsNameValuePair.push({'Name':'Screen Entry', 'Value':'&#59434;'});
            iconsNameValuePair.push({'Name':'Users', 'Value':'&#59435;'});
            iconsNameValuePair.push({'Name':'Phone Landscape', 'Value':'&#59436;'});
            iconsNameValuePair.push({'Name':'Phone Tall', 'Value':'&#59437;'});
            iconsNameValuePair.push({'Name':'Camera', 'Value':'&#59438;'});
            iconsNameValuePair.push({'Name':'Flag', 'Value':'&#59439;'});
            iconsNameValuePair.push({'Name':'Phone Entry/Phone Upload', 'Value':'&#59440;'});
            iconsNameValuePair.push({'Name':'Re-Do', 'Value':'&#59442;'});
            iconsNameValuePair.push({'Name':'Reload/Repeat/Refresh', 'Value':'&#59443;'});
            iconsNameValuePair.push({'Name':'Arrow Out Left', 'Value':'&#59444;'});
            iconsNameValuePair.push({'Name':'Synchronize', 'Value':'&#59445;'});
            iconsNameValuePair.push({'Name':'Right Arrow', 'Value':'&#59446;'});
            iconsNameValuePair.push({'Name':'Synchronize/Reload', 'Value':'&#59447;'});
            iconsNameValuePair.push({'Name':'Bullets (No Bullets)', 'Value':'&#59448;'});
            iconsNameValuePair.push({'Name':'Magnifying Glass', 'Value':'&#59449;'});
            iconsNameValuePair.push({'Name':'Transfer Out', 'Value':'&#59450;'});
            iconsNameValuePair.push({'Name':'SMS', 'Value':'&#59451;'});
            iconsNameValuePair.push({'Name':'Share Icon', 'Value':'&#59452;'});
            iconsNameValuePair.push({'Name':'Up and Down', 'Value':'&#59453;'});
            iconsNameValuePair.push({'Name':'Sun', 'Value':'&#59454;'});
            iconsNameValuePair.push({'Name':'Completed/Ok', 'Value':'&#59455;'});
            iconsNameValuePair.push({'Name':'Tablet Landscape', 'Value':'&#59456;'});
            iconsNameValuePair.push({'Name':'Tablet Tall', 'Value':'&#59457;'});
            iconsNameValuePair.push({'Name':'New', 'Value':'&#59458;'});
            iconsNameValuePair.push({'Name':'Undo', 'Value':'&#59459;'});
            iconsNameValuePair.push({'Name':'Up Arrow', 'Value':'&#59460;'});
            iconsNameValuePair.push({'Name':'Upload', 'Value':'&#59461;'});
            iconsNameValuePair.push({'Name':'Layout', 'Value':'&#59462;'});
            iconsNameValuePair.push({'Name':'Bullets (Symbols)', 'Value':'&#59463;'});
            iconsNameValuePair.push({'Name':'Checklist Checked', 'Value':'&#59464;'});
            iconsNameValuePair.push({'Name':'Split', 'Value':'&#59465;'});
            iconsNameValuePair.push({'Name':'Open Lock', 'Value':'&#59466;'});
            iconsNameValuePair.push({'Name':'Calendar (Week)', 'Value':'&#59467;'});
            iconsNameValuePair.push({'Name':'Street Signs', 'Value':'&#59468;'});
            iconsNameValuePair.push({'Name':'Applications', 'Value':'&#59469;'});
            iconsNameValuePair.push({'Name':'Up Arrow Back to the Future', 'Value':'&#59470;'});
            iconsNameValuePair.push({'Name':'Open Folder', 'Value':'&#59471;'});
            iconsNameValuePair.push({'Name':'Chevrons Right', 'Value':'&#59472;'});
            iconsNameValuePair.push({'Name':'Computer Synchronize', 'Value':'&#59473;'});
            iconsNameValuePair.push({'Name':'Barcode Reader', 'Value':'&#59474;'});
            iconsNameValuePair.push({'Name':'Open Book', 'Value':'&#59475;'});
            iconsNameValuePair.push({'Name':'Highway', 'Value':'&#59476;'});
            iconsNameValuePair.push({'Name':'Office', 'Value':'&#59477;'});
            iconsNameValuePair.push({'Name':'Brush', 'Value':'&#59478;'});
            iconsNameValuePair.push({'Name':'Palette', 'Value':'&#59479;'});
            iconsNameValuePair.push({'Name':'Document', 'Value':'&#59480;'});
            iconsNameValuePair.push({'Name':'Eye', 'Value':'&#59481;'});
            iconsNameValuePair.push({'Name':'Reload', 'Value':'&#59482;'});
            iconsNameValuePair.push({'Name':'Bullets List', 'Value':'&#59483;'});
            iconsNameValuePair.push({'Name':'Hard Drive', 'Value':'&#59484;'});
            iconsNameValuePair.push({'Name':'Double Arrow Left', 'Value':'&#59485;'});
            iconsNameValuePair.push({'Name':'User Stats', 'Value':'&#59486;'});
            iconsNameValuePair.push({'Name':'User Pin', 'Value':'&#59487;'});
            iconsNameValuePair.push({'Name':'Document Transfer', 'Value':'&#59488;'});
            iconsNameValuePair.push({'Name':'Copies', 'Value':'&#59489;'});
            iconsNameValuePair.push({'Name':'Cloud', 'Value':'&#59490;'});
            iconsNameValuePair.push({'Name':'Contact Card', 'Value':'&#59491;'});
            iconsNameValuePair.push({'Name':'Wrench', 'Value':'&#59492;'});
            iconsNameValuePair.push({'Name':'Thumbs Down', 'Value':'&#59493;'});
            iconsNameValuePair.push({'Name':'Cut', 'Value':'&#59494;'});
            iconsNameValuePair.push({'Name':'Paste', 'Value':'&#59495;'});
            iconsNameValuePair.push({'Name':'Copy (Clipboard)', 'Value':'&#59496;'});
            iconsNameValuePair.push({'Name':'Wireless Down', 'Value':'&#59497;'});
            iconsNameValuePair.push({'Name':'Lightning', 'Value':'&#59498;'});
            iconsNameValuePair.push({'Name':'User Delete', 'Value':'&#59499;'});
            iconsNameValuePair.push({'Name':'Delete Email', 'Value':'&#59500;'});
            iconsNameValuePair.push({'Name':'Wireless Up', 'Value':'&#59501;'});
            iconsNameValuePair.push({'Name':'Form', 'Value':'&#59502;'});
            iconsNameValuePair.push({'Name':'USB', 'Value':'&#59503;'});
            iconsNameValuePair.push({'Name':'Cancel', 'Value':'&#59504;'});
            iconsNameValuePair.push({'Name':'Home/House', 'Value':'&#59505;'});
            iconsNameValuePair.push({'Name':'Closed Folder', 'Value':'&#59506;'});
            iconsNameValuePair.push({'Name':'Puzzle Piece', 'Value':'&#59507;'});
            iconsNameValuePair.push({'Name':'Trash', 'Value':'&#59508;'});
            iconsNameValuePair.push({'Name':'Pie Chart', 'Value':'&#59509;'});
            iconsNameValuePair.push({'Name':'Accounts/Buildings', 'Value':'&#59510;'});
            iconsNameValuePair.push({'Name':'Chain/Links', 'Value':'&#59511;'});
            iconsNameValuePair.push({'Name':'Maximize', 'Value':'&#59512;'});
            iconsNameValuePair.push({'Name':'Note book/Agenda', 'Value':'&#59513;'});
            iconsNameValuePair.push({'Name':'Information', 'Value':'&#59514;'});
            iconsNameValuePair.push({'Name':'VCR', 'Value':'&#59515;'});
            iconsNameValuePair.push({'Name':'Burguer Menu', 'Value':'&#59520;'});
            iconsNameValuePair.push({'Name':'Power off', 'Value':'&#59521;'});
            iconsNameValuePair.push({'Name':'Un-link', 'Value':'&#59522;'});
            iconsNameValuePair.push({'Name':'Sections', 'Value':'&#59523;'});
            iconsNameValuePair.push({'Name':'Builiding/Drop Down Menus', 'Value':'&#59524;'});
            iconsNameValuePair.push({'Name':'Underline', 'Value':'&#59525;'});
            iconsNameValuePair.push({'Name':'Zoom In', 'Value':'&#59526;'});
            iconsNameValuePair.push({'Name':'Cancel/Stop/Prohibited', 'Value':'&#59527;'});
            iconsNameValuePair.push({'Name':'Drop Downs/Ribbons/Down Bar Charts', 'Value':'&#59528;'});
            iconsNameValuePair.push({'Name':'Sync Devices', 'Value':'&#59529;'});
            iconsNameValuePair.push({'Name':'Down', 'Value':'&#59530;'});
            iconsNameValuePair.push({'Name':'Up', 'Value':'&#59531;'});
            iconsNameValuePair.push({'Name':'Disk Update', 'Value':'&#59532;'});
            iconsNameValuePair.push({'Name':'Down Chevron', 'Value':'&#59533;'});
            iconsNameValuePair.push({'Name':'Up Chevron', 'Value':'&#59534;'});
            iconsNameValuePair.push({'Name':'Calendar Month', 'Value':'&#59535;'});
            iconsNameValuePair.push({'Name':'Spiral Notebook/Notepad', 'Value':'&#59536;'});
            iconsNameValuePair.push({'Name':'Bullets, Sub Bullets', 'Value':'&#59537;'});
            iconsNameValuePair.push({'Name':'Half a Dozen', 'Value':'&#59538;'});
            iconsNameValuePair.push({'Name':'Zoom Out', 'Value':'&#59539;'});
            iconsNameValuePair.push({'Name':'Minimize', 'Value':'&#59540;'});
            iconsNameValuePair.push({'Name':'Markup', 'Value':'&#59541;'});
            iconsNameValuePair.push({'Name':'Add Document', 'Value':'&#59542;'});
            iconsNameValuePair.push({'Name':'Rocket Ship', 'Value':'&#59543;'});
            iconsNameValuePair.push({'Name':'Form/Bullets', 'Value':'&#59544;'});
            iconsNameValuePair.push({'Name':'Center Text', 'Value':'&#59545;'});
            component.set("v.iconsNameValuePair", iconsNameValuePair);
        }
    }
})