global interface ACN_NavigationProviderService {
    /*
    ACN_NavigationLibrary.NavigationList GetNavigationList (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList GoUp (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList GoPrevious (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList GoNext (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList GoLast (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList SavePreference (ACN_NavigationLibrary.NavigationRequest request);
    ACN_NavigationLibrary.NavigationList LoadPreference (ACN_NavigationLibrary.NavigationRequest request);
*/
}