@isTest
Private class ACN_ScoringLibraryTest {
    
    @isTest static void testScoringLibraryTestMethod(){
        test.startTest();
        ACN_ScoringLibrary testmethod1= new ACN_ScoringLibrary();
        ACN_ScoringLibrary.ScoringRequest score = new ACN_ScoringLibrary.ScoringRequest();
        ACN_ScoringLibrary.ScoringResponse scoreresponse = new ACN_ScoringLibrary.ScoringResponse();
        ACN_ScoringLibrary.Scoring scoring = new ACN_ScoringLibrary.Scoring();
        Test.stopTest();
    }
}