@isTest
private class ACN_ChartLibraryTest {
 @isTest static void testChatLibraryTestMethod(){
    
        test.startTest();
        ACN_ChartLibrary.ChartRequest testmethod1= new ACN_ChartLibrary.ChartRequest();
        ACN_ChartLibrary.ChartResponse chartResponseTest = new ACN_ChartLibrary.ChartResponse();
        ACN_ChartLibrary.ChartSeries chartSeriesTest = new ACN_ChartLibrary.ChartSeries();
        ACN_ChartLibrary.ChartDataSet chartDataSetTest = new ACN_ChartLibrary.ChartDataSet();
        Test.stopTest();
    }

}