@isTest
public class ACN_ChartDataProviderTest {
    @isTest static void testChatLibraryTestMethod(){
        
        test.startTest();
        ACN_ChartDataProvider acn = new ACN_ChartDataProvider('ACN_ChartDataProvider');
       // ACN_ChartLibrary.ChartRequest testmethod1= new ACN_ChartLibrary.ChartRequest();
 
        Test.stopTest();
    }
  /*  @isTest static void testChatLibraryTestMethod1(){
        
        test.startTest();
        ACN_ChartDataProvider acn = new ACN_ChartDataProvider('ACN_ChartDataProvider');
        ACN_ChartLibrary.ChartRequest testmethod1= new ACN_ChartLibrary.ChartRequest();
        acn.GetChartResponse(testmethod1);
        Test.stopTest();
    }
    @isTest static void testChatLibraryTestMethod2(){
        
        test.startTest();
        ACN_ChartDataProvider acn = new ACN_ChartDataProvider('ACN_ChartDataProvider');
        ACN_ChartLibrary.ChartRequest testmethod1= new ACN_ChartLibrary.ChartRequest();
        acn.SavePreference(testmethod1);
        Test.stopTest();
    }*/

}